server:
  port: 9094

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      repositories:
          enabled: true