server:
  port: 9094

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: "http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka"

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:Halifaxpass1@atlas-cluster.nww4umn.mongodb.net/?retryWrites=true&w=majority #mongodb://localhost:27017/orderdb
      repositories:
          enabled: true
      host: atlas-cluster.nww4umn.mongodb.net
      port: 27017
      database: orderdb